name: Clean webpack cache

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install gh cache extension
        run: gh extension install actions/gh-actions-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCHES=($(git ls-remote --heads | cut -d$'\t' -f2))
          echo branches : ${BRANCHES[@]}

          for BRANCH in "${BRANCHES[@]}"
          do
            CACHES=($(gh actions-cache list -B $BRANCH --limit 100 | grep Linux-webpack |  cut -d$'\t' -f1))
            echo number of caches $BRANCH : "${#CACHES[@]}"
            if [ "${#CACHES[@]}" -lt 2 ]; then
              echo "$BRANCH : no cache to delete"
            else
              echo "$BRANCH : deleting irrelevant cache"
              # parallel -j 5 gh actions-cache delete --confirm ::: ${CACHES[@]:1}
            fi
          done
